services:

  mysql-database:
    image: "mysql:latest"
    container_name: "mysql-database"
    ports:
      - "3306:3306"
    volumes:
      - "./sql/schema:/docker-entrypoint-initdb.d"
      - "./sql/data:/var/lib/mysql"
    environment:
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=user"
      - "MYSQL_DATABASE=users"
      - "MYSQL_ROOT_PASSWORD=root"
    networks:
      - secure-network
    tty: true
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  secure-network:
    driver: bridge